### ISSUE TITLE
Reload, Restart Command not readded

### ISSUE THREAD

**Issue by danielnehrig** [famiu/nvim-reload#1]
When executing Reload
the Command alias for the reload function disappears
but reload still works over module require

**Comment by famiu** [comment]
Does it work now?

**Comment by lsrdg** [comment]
The last commit fixed it for me. @famiu . Thanks for the plugin!

**Comment by famiu** [comment]
@lsrdg you're welcome. Glad to be of help!

@danielnehrig Does it work for you?

**Comment by famiu** [comment]
@lsrdg also, unrelated but I just made a commit to use `source` instead of `luafile` if init file is written in VimL instead of Lua. I did that because I noticed you had to fork the repo just for that, so I made it a feature

**Comment by lsrdg** [comment]
@famiu, amazing! At the moment, I have an `init.vim` file (with maps and options) that sources  lua files. The use of  `source` in instead of `luafile` fixed the issue for me, but I didn't test what would happen the other way around (and that's why I didn't open a PR). Let me know if you need any info from my side and thanks for taking the time.
I might come back with a PR for the docs though. (:

**Comment by famiu** [comment]
> Let me know if you need any info from my side and thanks for taking the time.

Thanks, I will. And you're welcome.
> I might come back with a PR for the docs though. (:

That would be appreciated

**Comment by danielnehrig** [comment]
yes it works now thanks
close this when ever you feel like
